[build-dependencies]
vergen = '3'

[package]
authors = ['Ricardo Rius <ricardo@rius.info>']
build = 'build.rs'
edition = '2018'
name = 'identitychain'
version = '2.0.0'

[dependencies]
derive_more = "0.14.0"
futures = "0.1"
log = "0.4"
tokio = "0.1"
exit-future = "0.1"
parking_lot = "0.7.1"
parity-codec = "3.3"
trie-root = "0.12.2"

[dependencies.basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-basic-authorship'
rev = 'dfcc0850ab581a4804921904f8015bacf2e63ea7'

[dependencies.consensus]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-aura'
rev = 'dfcc0850ab581a4804921904f8015bacf2e63ea7'

[dependencies.ctrlc]
features = ['termination']
version = '3.0'

[dependencies.inherents]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-inherents'
rev = 'dfcc0850ab581a4804921904f8015bacf2e63ea7'

[dependencies.network]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-network'
rev = 'dfcc0850ab581a4804921904f8015bacf2e63ea7'

[dependencies.identitychain-runtime]
path = 'runtime'

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = 'dfcc0850ab581a4804921904f8015bacf2e63ea7'

[dependencies.sr-io]
git = 'https://github.com/paritytech/substrate.git'
rev = 'dfcc0850ab581a4804921904f8015bacf2e63ea7'

[dependencies.substrate-cli]
git = 'https://github.com/paritytech/substrate.git'
rev = 'dfcc0850ab581a4804921904f8015bacf2e63ea7'

[dependencies.substrate-client]
git = 'https://github.com/paritytech/substrate.git'
rev = 'dfcc0850ab581a4804921904f8015bacf2e63ea7'

[dependencies.substrate-executor]
git = 'https://github.com/paritytech/substrate.git'
rev = 'dfcc0850ab581a4804921904f8015bacf2e63ea7'

[dependencies.substrate-service]
git = 'https://github.com/paritytech/substrate.git'
rev = 'dfcc0850ab581a4804921904f8015bacf2e63ea7'

[dependencies.transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-transaction-pool'
rev = 'dfcc0850ab581a4804921904f8015bacf2e63ea7'

[[bin]]
name = 'identitychain'
path = 'src/main.rs'
